const axios = require("axios");
const api = axios.create({ baseURL: process.env.DID_API_BASE_URL || "https://api.d-id.com", timeout: 30000 });
const headers = () => ({ Authorization: `Basic ${process.env.DID_API_KEY}`, "Content-Type": "application/json" });
exports.createTalk = async ({ imageUrl, audioUrl }) => (await api.post("/talks", { source_url: imageUrl, script: { type: "audio", audio_url: audioUrl }, config: { fluent: true, pad_audio: 0 } }, { headers: headers() })).data;
exports.getTalk = async ({ talkId }) => (await api.get(`/talks/${talkId}`, { headers: headers() })).data;
exports.createStream = async ({ avatarUrl }) => (await api.post("/talks/streams", { source_url: avatarUrl }, { headers: headers() })).data;
exports.submitSdpAnswer = async ({ streamId, sessionId, answer }) => (await api.post(`/talks/streams/${streamId}/sdp`, { answer, session_id: sessionId }, { headers: headers() })).data;
exports.addIceCandidate = async ({ streamId, sessionId, candidate, sdpMid, sdpMLineIndex }) => (await api.post(`/talks/streams/${streamId}/ice`, { candidate, sdpMid, sdpMLineIndex, session_id: sessionId }, { headers: headers() })).data;
exports.speakText = async ({ streamId, sessionId, text }) => (await api.post(`/talks/streams/${streamId}`, { script: { type: "text", input: text, provider: { type: "microsoft", voice_id: "en-US-JennyNeural" } }, config: { fluent: true, pad_audio: 0 }, session_id: sessionId }, { headers: headers() })).data;
exports.speakAudio = async ({ streamId, sessionId, audioUrl }) => (await api.post(`/talks/streams/${streamId}`, { script: { type: "audio", audio_url: audioUrl }, config: { fluent: true, pad_audio: 0 }, session_id: sessionId }, { headers: headers() })).data;
exports.deleteStream = async ({ streamId, sessionId }) => (await api.delete(`/talks/streams/${streamId}`, { headers: headers(), data: { session_id: sessionId } })).data;
